<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
df = pd.DataFrame({
    'c1' : ['a','a','b','a','b'],
    'c2' : [1,1,1,2,2],
    'c3' : [1,1,2,2,2]
})
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [39]:
df_dup = df.duplicated()
print(df_dup)

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [40]:
col_dup = df['c2'].duplicated()
print(col_dup)

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [41]:
df2 = df.drop_duplicates()
print(df2)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [42]:
df3 = df.drop_duplicates(subset=['c2','c3'])
print(df3)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [43]:
import pandas as pd
import numpy as np

In [44]:
import seaborn as sns
df = sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [45]:
mpg_to_kpl = 1.60934 / 3.78541

df['kpl'] = df['mpg'] * mpg_to_kpl
print(df.head(3))
print('\n')

df['kpl'] = df['kpl'].round(2)
print(df.head(3))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name       kpl
0          70    usa  chevrolet chevelle malibu  7.652571
1          70    usa          buick skylark 320  6.377143
2          70    usa         plymouth satellite  7.652571


    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name   kpl
0          70    usa  chevrolet chevelle malibu  7.65
1          70    usa          buick skylark 320  6.38
2          70    usa         plymouth satellite  7.65

In [46]:
print(df.dtypes)
print('\n')

print(df['horsepower'].unique())
print('\n')

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
name             object
kpl             float64
dtype: object


[130. 165. 150. 140. 198. 220. 215. 225. 190. 170. 160.  95.  97.  85.
  88.  46.  87.  90. 113. 200. 210. 193.  nan 100. 105. 175. 153. 180.
 110.  72.  86.  70.  76.  65.  69.  60.  80.  54. 208. 155. 112.  92.
 145. 137. 158. 167.  94. 107. 230.  49.  75.  91. 122.  67.  83.  78.
  52.  61.  93. 148. 129.  96.  71.  98. 115.  53.  81.  79. 120. 152.
 102. 108.  68.  58. 149.  89.  63.  48.  66. 139. 103. 125. 133. 138.
 135. 142.  77.  62. 132.  84.  64.  74. 116.  82.]

In [47]:
print(df['origin'].unique())

['usa' 'japan' 'europe']

In [48]:
df['origin'].replace({1:'USA', 2:'EU', 3:'JAPAN'})

print(df['origin'].unique())
print(df['origin'].dtypes)

['usa' 'japan' 'europe']
object

In [49]:
df['origin'] = df['origin'].astype('category')
print(df['origin'].dtypes)

df['origin'] = df['origin'].astype('str')
print(df['origin'].dtypes)

category
object

In [50]:
print(df['model_year'].sample(3))

295    79
272    78
311    80
Name: model_year, dtype: int64

In [51]:
df['model_year'] = df['model_year'].astype('category')
print(df['model_year'].sample(3))

60     72
349    81
40     71
Name: model_year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [52]:
df['horsepower'].isnull().sum()

np.int64(6)

In [53]:
df['horsepower'] = df['horsepower'].replace('?',np.nan)
df.dropna(subset=['horsepower'], axis=0,  inplace=True)

In [54]:
df['horsepower'].isnull().sum()

np.int64(0)

In [55]:
df['horsepower'].dtypes

dtype('float64')

In [56]:
df['horsepower'] = df['horsepower'].astype('float')

In [57]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]

In [58]:
bin_names = ['Low output', 'Normal output', 'High output']

df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins = bin_dividers,
                      labels = bin_names,
                      include_lowest = True)
print(df[['horsepower','hp_bin']].head(15))

    horsepower         hp_bin
0        130.0  Normal output
1        165.0  Normal output
2        150.0  Normal output
3        150.0  Normal output
4        140.0  Normal output
5        198.0    High output
6        220.0    High output
7        215.0    High output
8        225.0    High output
9        190.0    High output
10       170.0    High output
11       160.0  Normal output
12       150.0  Normal output
13       225.0    High output
14        95.0     Low output

In [59]:
import seaborn as sns
df = sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [60]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [61]:
df['horsepower'].replace('?',np.nan)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float')

In [63]:
count, bin_dividers = np.histogram(df['horsepower'],bins=3)
bin_names = ['low_output', 'normal_output', 'high_output']

In [64]:
df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins = bin_dividers,
                      labels = bin_names,
                      include_lowest=True)

horsepower_dummies = pd.get_dummies(df['hp_bin']).astype('int')
print(horsepower_dummies.head(15))

    low_output  normal_output  high_output
0            0              1            0
1            0              1            0
2            0              1            0
3            0              1            0
4            0              1            0
5            0              0            1
6            0              0            1
7            0              0            1
8            0              0            1
9            0              0            1
10           0              0            1
11           0              1            0
12           0              1            0
13           0              0            1
14           1              0            0

In [65]:
print(df.horsepower.describe())
print('\n')

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [66]:
df.horsepower = df.horsepower / abs(df.horsepower.max())

print(df.horsepower.head())
print('\n')
print(df.horsepower.describe())

0    0.565217
1    0.717391
2    0.652174
3    0.652174
4    0.608696
Name: horsepower, dtype: float64


count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

In [67]:
min_x = df.horsepower - df.horsepower.min()
min_max = df.horsepower.max() - df.horsepower.min()
df.horsepower = min_x / min_max

print(df.horsepower.describe())

count    392.000000
mean       0.317768
std        0.209191
min        0.000000
25%        0.157609
50%        0.258152
75%        0.434783
max        1.000000
Name: horsepower, dtype: float64